#!/bin/bash
clear

# Função para verificar e instalar pacotes
install_if_missing() {
    local pkg="$1"
    if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
        echo "Instalando $pkg..."
        apt-get install -y "$pkg" >/dev/null 2>&1 || {
            echo -e "\033[1;31mErro ao instalar $pkg\033[0m"
            exit 1
        }
    else
        echo "$pkg já está instalado."
    fi
}

# Função para instalar pacotes iniciais
install_initial_packages() {
    echo "Instalando pacotes iniciais..."
    apt-get install -y lolcat iproute2 toilet curl git figlet boxes net-tools procps sysstat >/dev/null 2>&1 || {
        echo -e "\033[1;31mErro ao instalar pacotes iniciais\033[0m"
        exit 1
    }
}

# Instalação silenciosa de pacotes
install_initial_packages

# Verificação se o usuário é root
cd $HOME
if [[ "$(whoami)" != "root" ]]; then
    echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mVOCÊ PRECISA EXECUTAR A INSTALAÇÃO DO SCRIPT COMO USUÁRIO ROOT\033[0m"
    rm $HOME/Plus >/dev/null 2>&1
    exit 1
fi

# Função barra de progresso com limpeza robusta
fun_bar() {
    comando[0]="$1"
    comando[1]="$2"
    # Criar arquivo temporário único usando mktemp
    local temp_file
    temp_file=$(mktemp "$HOME/fim.XXXXXX") || {
        echo -e "\033[1;31mErro ao criar arquivo temporário\033[0m"
        exit 1
    }
    # Armadilha para remover o arquivo temporário em caso de interrupção
    trap 'rm -f "$temp_file" >/dev/null 2>&1' EXIT INT TERM
    (
        # Executar comandos e criar arquivo temporário
        ${comando[0]} -y >/dev/null 2>&1
        ${comando[1]} -y >/dev/null 2>&1
        touch "$temp_file" >/dev/null 2>&1
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne    "\033[1;31m   ❪\033[1;33mAGUARDE \033[5;37m>\033[5;37m>\033[5;37m>\033[5;37m> \033[1;93m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[1;92m■"
            sleep 0.1s
        done
        if [[ -e "$temp_file" ]]; then
            rm -f "$temp_file" >/dev/null 2>&1 && break
        fi
        echo -e "\033[1;93m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "\033[1;31m   ❪\033[1;33mAGUARDE \033[5;37m>\033[5;37m>\033[5;37m>\033[5;37m> \033[1;93m["
    done
    echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}

# Redefinir a exibição do terminal
tput reset
echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
echo -e "\033[0;34m┃\E[41;1;37m               ⇱ SCRIPT SSHPLUS PRO ⇲             \E[0m\033[0;34m┃"
echo -e "\033[0;34m┠━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┨\033[0m"
echo -e "\033[0;34m┃                                                  \033[0;34m┃"  
echo -e "\033[0;34m┃           \033[1;31mATENCAO! \033[1;37mESSE SCRIPT IRA !             \033[0;34m┃"
echo -e "\033[0;34m┃                                                  \033[0;34m┃"
echo -e "\033[0;34m┃\033[1;32m• \033[1;37mINSTALAR UM CONJUNTO DE SCRIPTS COMO FERRAMENTAS\033[0;34m┃"
echo -e "\033[0;34m┃\033[1;37m  PARA O GERENCIAMENTO DE REDE, SISTEMA E USUARIOS\033[0;34m┃"
echo -e "\033[0;34m┃                                                  \033[0;34m┃"
echo -e "\0330;34m┃\033[1;32m• \033[1;32mDICA! \033[1;37mULTILIZE O TEMA DARK EM SEU TERMINAL PARA \033[0;34m┃"
echo -e "\033[0;34m┃\033[1;37m  UMA MELHOR EXPERIÊNCIA E VISUALIZACAO DO MESMO! \033[0;34m┃"
echo -e "\033[0;34m┃                                                  \033[0;34m┃"
echo -e "\033[0;34m┠━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┨\033[0m"
echo -e "\033[0;34m┃\033[1;37m               by:@TURBONET2023                   \E[0m\033[0;34m┃"
echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"           
echo ""
#-----------------------------------------------------------------------------------------------------------------
wget -O /root/install https://raw.githubusercontent.com/PhoenixxZ2023/NEW-SSHPLUS/refs/heads/main/script/install > /dev/null 2>&1
chmod +x /root/install >/dev/null 2>&1
/root/install >/dev/null 2>&1
sleep 3s
echo "/bin/menu" >/bin/h && chmod +x /bin/h >/dev/null 2>&1
rm versao* >/dev/null 2>&1
wget https://raw.githubusercontent.com/PhoenixxZ2023/NEW-SSHPLUS/main/Install/versao >/dev/null 2>&1
rm v2raymanager >/dev/null 2>&1
wget https://raw.githubusercontent.com/PhoenixxZ2023/NEW-SSHPLUS/main/Modulos/v2raymanager >/dev/null 2>&1
wget https://raw.githubusercontent.com/PhoenixxZ2023/NEW-SSHPLUS/main/Modulos/botteste.sh >/dev/null 2>&1
chmod 777 v2raymanager >/dev/null 2>&1
chmod 777 botteste.sh >/dev/null 2>&1
mkdir $HOME/BOT >/dev/null 2>&1
cd $HOME/BOT
wget https://raw.githubusercontent.com/PhoenixxZ2023/NEW-SSHPLUS/main/Modulos/ShellBot.sh >/dev/null 2>&1
chmod 777 ShellBot.sh >/dev/null 2>&1
cd >/dev/null 2>&1
chmod 777 licence >/dev/null 2>&1
mkdir /etc/rec >/dev/null 2>&1
cd /etc/rec
wget https://raw.githubusercontent.com/PhoenixxZ2023/NEW-SSHPLUS/main/Modulos/licence >/dev/null 2>&1
chmod 777 licence >/dev/null 2>&1
cd >/dev/null 2>&1
#-----------------------------------------------------------------------------------------------------------------
echo ""
[[ -f "$HOME/usuarios.db" ]] && {
tput reset
echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
echo -e "\033[0;34m┃                   \033[1;37m• \033[1;31mATENCAO \033[1;37m•                   \033[0;34m┃"
echo -e "\033[0;34m┠━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┨\033[0m"
echo -e "\033[0;34m┃\033[1;37mUMA BASE DE DADOS DE USUÁRIO \033[1;32m(usuarios.db) \033[1;37mFoi   \033[0;34m┃" 
echo -e "\033[0;34m┃\033[1;37mENCONTRADA! DESEJA MANTE-LA PRESERVANDO O LIMITE \033[0;34m┃"
echo -e "\033[0;34m┃\033[1;37mDE CONEXÕES SIMULTÂNEAS DE USUARIOS? OU DESEJA   \033[0;34m┃"
echo -e "\033[0;34m┃\033[1;37mCRIAR UMA NOVA BASE ?                            \033[0;34m┃"
echo -e "\033[0;34m┠━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┨\033[0m"
echo -e "\033[0;34m┃\033[1;37m[\033[1;31m1\033[1;37m] \033[1;37mMANTER BASE DE DADOS ATUAIS                  \033[0;34m┃"
echo -e "\033[0;34m┃\033[1;37m[\033[1;31m2\033[1;37m] \033[1;37mCRIAR UMA NOVA BASE DE DADOS                 \033[0;34m┃"
echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"
echo ""
tput setaf 2 ; tput bold ; read -p "Opção ?: " -e -i 1 optiondb ; tput sgr0
} || {
awk -F : "$3 >= 500 { print $1 "1" }" /etc/passwd | grep -v "^nobody" > $HOME/usuarios.db
}
[[ "$optiondb" = "2" ]] && awk -F : "$3 >= 500 { print $1 " 1" }" /etc/passwd | grep -v "^nobody" > $HOME/usuarios.db

# Redefinir a exibição do terminal
tput reset
echo -e "\E[38;5;36m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
echo -e "\E[38;5;36m┃\E[44;1;37m            AGUARDE A INSTALAÇÃO               \E[0m\E[38;5;36m┃"
echo -e "\E[38;5;36m╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"
echo ""
echo -e "       \033[1;91m[\033[1;31m⚠️ \033[1;37m] \033[1;97mATUALIZANDO SISTEMA \033[1;37m[\033[1;31m⚠️ \033[1;91m]\033[0m"
echo ""
echo -e "  \033[1;93mATUALIZAÇÕES COSTUMAM DEMORAR UM POUCO!\033[0m"
echo ""

# Definir a função de atualização do sistema
fun_attlist() {
    # Criar diretório oculto, se não existir
    if [[ ! -d /usr/share/.plus ]]; then
        mkdir /usr/share/.plus
    fi

    # Registrar a data da atualização
    echo "crz: $(date)" > /usr/share/.plus/.plus
}

# Executar a função de atualização do sistema com barra de progresso
fun_bar "fun_attlist"

# Redefinir a exibição do terminal
tput reset
echo -e "\E[38;5;18m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
echo -e "\E[38;5;18m┃\E[44;1;37m            AGUARDE A INSTALAÇÃO               \E[0m\E[38;5;18m┃"
echo -e "\E[38;5;18m╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"
echo ""
echo -e "       \033[1;91m[\033[1;31m⚠️ \033[1;91m] \033[1;97mINSTALANDO PYTHON \033[1;91m[\033[1;31m⚠️ \033[1;91m] \033[0m"
echo ""
echo -e "        \033[1;93mCOSTUMA DEMORAR UM POUCO!\033[0m"
echo ""

# Função para instalar Python3 baseado na versão do sistema
install_python3() {
    if command -v python3 >/dev/null 2>&1 && dpkg-query -W -f='${Status}' socat 2>/dev/null | grep -q "ok installed"; then
        echo "Python3 e socat já estão instalados."
    else
        . /etc/os-release
        if { [[ "$ID" == "ubuntu" && "$VERSION_ID" == "20.04" ]] || [[ "$ID" == "debian" && "$VERSION_ID" == "11" ]]; }; then
            apt-get install -y python3.8 python3-pip socat >/dev/null 2>&1 || {
                echo -e "\033[1;31mErro ao instalar Python3.8 ou socat\033[0m"
                exit 1
            }
            update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 >/dev/null 2>&1
            update-alternatives --set python3 /usr/bin/python3.8 >/dev/null 2>&1
        elif { [[ "$ID" == "ubuntu" && "$VERSION_ID" == "22.04" ]] || [[ "$ID" == "debian" && "$VERSION_ID" == "12" ]]; }; then
            apt-get install -y python3.10 python3-pip socat >/dev/null 2>&1 || {
                echo -e "\033[1;31mErro ao instalar Python3.10 ou socat\033[0m"
                exit 1
            }
            update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 >/dev/null 2>&1
            update-alternatives --set python3 /usr/bin/python3.10 >/dev/null 2>&1
        else
            echo -e "\033[1;31m[SISTEMA NÃO SUPORTADO] Apenas Ubuntu 20.04, Ubuntu 22.04, Debian 11 e Debian 12 são compatíveis.\033[0m"
            exit 1
        fi
    fi
}

# Chama a função de instalação do Python3 com barra de progresso
fun_bar "install_python3"

# Redefinir a exibição do terminal
tput reset
echo -e "\E[38;5;18m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
echo -e "\E[38;5;18m┃\E[44;1;37m            AGUARDE A INSTALAÇÃO               \E[0m\E[38;5;18m┃"
echo -e "\E[38;5;18m╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"
echo ""
echo -e "       \033[1;91m[\033[1;31m⚠️ \033[1;91m] \033[1;97mINSTALANDO PACOTES  \033[1;91m[\033[1;31m⚠️ \033[1;91m] \033[0m"
echo ""
echo -e " \033[1;93mALGUNS PACOTES SÃO EXTREMAMENTE NECESSÁRIOS!\033[0m"
echo ""

# Função para instalar pacotes necessários
inst_pct() {
  if [[ $EUID -ne 0 ]]; then
    echo "Este script precisa ser executado como root."
    exit 1
  fi
  _pacotes=("bc" "screen" "nano" "unzip" "lsof" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "firewalld")
  for _prog in "${_pacotes[@]}"; do
    if ! dpkg -l | grep -q "^ii  $_prog "; then
      echo "Instalando pacote: $_prog"
      apt install -y $_prog
    else
      echo "Pacote já instalado: $_prog"
    fi
  done
  # Instalando o Speedtest-CLI
    echo -e "\e[1;32mINSTALANDO SPEEDTEST-CLI...\e[0m"
    pip3 install speedtest-cli || {
        echo -e "\e[1;31mFALHA AO INSTALAR SPEEDTEST-CLI\e[0m"
        exit 1
    }

  # Configurar regras do firewall
  sudo firewall-cmd --zone=public --permanent --add-port=80/tcp
  sudo firewall-cmd --zone=public --permanent --add-port=81/tcp
  sudo firewall-cmd --zone=public --permanent --add-port=443/tcp
  sudo firewall-cmd --zone=public --permanent --add-port=2053/tcp
  sudo firewall-cmd --zone=public --permanent --add-port=1194/tcp
  sudo firewall-cmd --zone=public --permanent --add-port=8080/tcp
  sudo firewall-cmd --zone=public --permanent --add-port=8989/tcp
  sudo firewall-cmd --zone=public --permanent --add-port=5454/tcp
  sudo firewall-cmd --zone=public --permanent --add-port=8888/tcp
  sudo firewall-cmd --zone=public --permanent --add-port=7300/udp
  sudo firewall-cmd --reload
}
fun_bar 'inst_pct'

# Configurar regras no UFW, se estiver instalado
if [[ -f "/usr/sbin/ufw" ]]; then
  ufw allow 443/tcp
  ufw allow 80/tcp
  ufw allow 3128/tcp
  ufw allow 8799/tcp
  ufw allow 8080/tcp
  echo "Configurações do UFW aplicadas."
fi

# Redefinir a exibição do terminal
tput reset
echo -e "\E[38;5;18m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
echo -e "\E[38;5;18m┃\E[44;1;37m            AGUARDE A INSTALAÇÃO               \E[0m\E[38;5;18m┃"
echo -e "\E[38;5;18m╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"
echo ""
echo -e "      \033[1;91m[\033[1;31m⚠️ \033[1;91m] \033[1;97mINSTALANDO MULTI-FERRAMENTAS \033[1;91m[\033[1;31m⚠️ \033[1;91m] \033[0m"
echo ""
inst_multi-ferra() {
# instalando rustyproxy by @UlekBR
bash <(wget -qO- https://raw.githubusercontent.com/PhoenixxZ2023/RustyProxyOnly/refs/heads/main/install.sh)

# Instalando checkuser multi-apps by @UlekBR
wget -qO /bin/checkuser https://raw.githubusercontent.com/PhoenixxZ2023/NEW-SSHPLUS/main/checkuser
chmod +x /bin/checkuser
}
fun_bar "inst_multi-ferra"

# Redefinir a exibição do terminal novamente
tput reset
echo -e "\E[38;5;18m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
echo -e "\E[38;5;18m┃\E[44;1;37m         INSTALANDO PACOTES DE REDE          \E[0m\E[38;5;18m┃"
echo -e "\E[38;5;18m╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"
echo ""
inst_pack_rede() {
fun_bar "sudo apt-get install -y lsof >/dev/null 2>&1"
fun_bar "sudo apt-get install -y htop >/dev/null 2>&1"
fun_bar "sudo apt-get install -y nload >/dev/null 2>&1"
fun_bar "sudo apt-get install -y zip >/dev/null 2>&1"
fun_bar "sudo apt-get install -y netcat >/dev/null 2>&1"
fun_bar "sudo apt install -y fail2ban >/dev/null 2>&1"
fun_bar "sudo systemctl start fail2ban >/dev/null 2>&1"
fun_bar "sudo systemctl enable fail2ban >/dev/null 2>&1"
fun_bar "sudo apt install lolcat figlet -y >/dev/null 2>&1"
}
fun_bar "inst_pack_rede"

# Redefinir a exibição do terminal
tput reset
echo -e "\E[38;5;18m╭━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╮\033[0m"
echo -e "\E[38;5;18m┃\E[44;1;37m         FINALIZANDO INSTALAÇÃO          \E[0m\E[38;5;18m┃"
echo -e "\E[38;5;18m╰━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╯\033[0m"
echo ""
echo -e "     \033[1;93mCONCLUINDO FUNÇÕES E DEFINIÇÕES! \033[0m"
echo ""
clear
echo ""
cd $HOME
echo ""
echo -e "\033[1;37;44m🚀 INSTALAÇÃO CONCLUÍDA! BEM-VINDO AO NEW-SSHPLUS 🎉 \033[0m"
echo ""
cd $HOME
echo "clear" >>/root/.bashrc
echo 'DATE=$(date +"%d-%m-%y")'
echo 'TIME=$(date +"%T")'
echo 'toilet -f smblock -F metal      "NEW-SSHPLUS 2025"'
echo 'echo -e "\033[01;31m\033[1;34m💻 NOME DO SERVIDOR : $HOSTNAME\033[0m"'
echo 'echo -e "\033[01;31m\033[1;34m⚙️ SERVIDOR LIGADO À : $(uptime -p)\033[0m"'
echo 'echo -e "\033[01;31m\033[1;34m📅 DATA : $(date +%d/%m/%Y)\033[0m"'
echo 'echo -e "\033[01;31m\033[1;34m⏰ HORA : $(date +%H:%M:%S)\033[0m"'
echo 'echo -e "\033[01;31m\033[1;34m📲 TELEGRAM OFICIAL: @TURBONET2023\033[0m"'
echo 'echo -e "\033[01;31m\033[1;34m📝 DIGITE ( menu ) PARA ENTRAR\033[0m"'
echo 'echo -e ""'
echo 'echo -e ""' >>/root/.bashrc
date=$(date "+%Y-%m-%d <> %H:%M:%S")
echo -e "\033[1;33m $system         $date"
echo ""
toilet -f smblock -F metal     "NEW-SSHPLUS 2025"
echo ""
echo -e "\033[01;31m\033[1;33m🚀 PARA INICIAR DIGITE: \033[1;32mmenu\033[0m"
echo -e "\033[01;31m\033[1;33m📢 MAIS INFORMAÇÕES: \033[1;31m(\033[1;36mTELEGRAM\033[1;31m) 👉 \033[1;37m@TURBONET2023\033[0m"
rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
